name = "cf-ai-personal-assistant"
main = "src/index.ts"
compatibility_date = "2025-01-21"

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "MEMORY"
class_name = "ConversationMemory"
script_name = "cf-ai-personal-assistant"

[[migrations]]
tag = "v1"
new_classes = ["ConversationMemory"]